EuCorro.MVC.Site/ViewModels/UsuarioViewModel.cs
using Eucorro.Domain.Enum;
using System;
using System.ComponentModel.DataAnnotations;

namespace EuCorro.MVC.Site.ViewModels
{
    public class UsuarioViewModel
    {
        [Key]
        public string UserId { get; set; }

        [ScaffoldColumn(false)]
        public int PerfilUsuarioId { get; set; }

        [Required]
        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Nome Completo")]
        public string Nome { get; set; }
                             
        [Required]
        [Display(Name = "Data Nascimento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime DataNascimento { get; set; }

        [Required]
        //[System.Web.Mvc.Remote("ValidarCPF", "Cadastro")]
        public string CPF { get; set; }
                        
        public Sexo Sexo { get; set; }

        [Required]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }

        [Required]
        [Display(Name = "Número")]
        public string Numero { get; set; }

        public string Complemento { get; set; }

        [Required]
        public string Bairro { get; set; }

        [Required]
        public string CEP { get; set; }

        [Display(Name = "País")]
        public int PaisId { get; set; }

        [Required]
        [Display(Name = "Cidade")]
        public int CidadeId { get; set; }

        [Required]
        [Display(Name = "Estado")]
        public int EstadoId { get; set; }

        [Required]
        public string Telefone { get; set; }

        [Required]
        public string Celular { get; set; }

        public string WhatsApp { get; set; }

        [ScaffoldColumn(false)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime DataCadastro { get; set; }
    }
}

EuCorro.MVC.Site/Areas/Admin/Controllers/UsuarioController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using EuCorro.App.Interface;
using Eucorro.Domain.Models;
using EuCorro.MVC.Site.ViewModels;
using EuCorro.Service;
using PagedList;
using EuCorro.Security.Filters;
using EuCorro.Security.Configuration;

namespace EuCorro.MVC.Site.Areas.Admin.Controllers
{
    [ClaimsAuthorize("Admin", "True")]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioApp _user;
        private ApplicationUserManager _userManager;

        public UsuarioController(ApplicationUserManager userManager, IUsuarioApp usuario)
        {
            _user = usuario;
            _userManager = userManager;
        }

        // GET: Admin/Úsuario
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //if (SessionManager.IsAuthenticated == false) return RedirectToAction("Login", "Account");

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var usuario = _user.GetAll().Where(x => x.PerfilUsuarioId.Equals(2));
            if (!String.IsNullOrEmpty(searchString))
            {
                usuario = usuario.Where(s => s.UserName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Nome_desc":
                    usuario = usuario.OrderByDescending(s => s.UserName);
                    break;
                //case "Data":
                //    fornecedores = fornecedores.OrderBy(s => s.Email);
                //    break;
                //case "Data_desc":
                //    fornecedores = fornecedores.OrderByDescending(s => s.Email);
                //    break;
                default:
                    usuario = usuario.OrderBy(s => s.UserName);
                    break;
            }

            const int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(usuario.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Úsuario/Create
        public ActionResult Create()
        {
            if (SessionManager.IsAuthenticated == false) return RedirectToAction("Login", "Account");

            ViewBag.Estado = _user.BuscarEstados().Select(x => new { x.EstadoId, x.Nome }).ToList();

            return View();
        }

        // POST: Admin/Úsuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioViewModel usuario)
        {
            if (_user.IsExistEmail(usuario.Email))
                ModelState.AddModelError("Email", "E-mail já cadastrado, tente outro...");

            var cpf = usuario.CPF;
            if (Functions.ValidaCpf(cpf) == false)
                ModelState.AddModelError("CPF", "CPF Inválido...");

            if (ModelState.IsValid)
            {
                var cliente = new Usuario();
                cliente.PerfilUsuarioId = 2;
                cliente.Email = usuario.Email;
                cliente.Senha = "@Senha2017";
                cliente.UserName = usuario.Nome.ToUpper();
                cliente.Numero = usuario.Numero;
                cliente.DataNascimento = usuario.DataNascimento;
                cliente.CPF = usuario.CPF;
                cliente.Brasileiro = 0;
                cliente.Sexo = usuario.Sexo;
                cliente.Contato = usuario.Nome;
                cliente.FoneContato = usuario.Telefone;
                cliente.Endereco = usuario.Endereco;
                cliente.Complemento = usuario.Complemento;
                cliente.Bairro = usuario.Bairro;
                cliente.CEP = usuario.CEP;
                cliente.PaisId = 1;
                cliente.CidadeId = usuario.CidadeId;
                cliente.EstadoId = usuario.EstadoId;
                cliente.Telefone = usuario.Telefone;
                cliente.Celular = usuario.Celular;
                cliente.WhatsApp = usuario.WhatsApp;
                _user.CadastraUsuario(cliente);
                return RedirectToAction("Index", "Usuario");
            }

            ViewBag.Estado = _user.BuscarEstados().Select(x => new { x.EstadoId, x.Nome }).ToList();
            return View(usuario);
        }

        // GET: Admin/Úsuario/Edit/5
        public ActionResult Edit(string email)
        {
            Usuario usuario = _user.RecuperarUsuarioPorEmail(email);
            if (usuario == null)
            {
                return HttpNotFound();
            }

            var cliente = new UsuarioViewModel();
            cliente.UserId = usuario.Id;
            cliente.PerfilUsuarioId = 2;
            cliente.Email = usuario.Email;
            cliente.Nome = usuario.UserName.ToUpper();
            cliente.Numero = usuario.Numero;
            cliente.DataNascimento = usuario.DataNascimento;
            cliente.CPF = usuario.CPF;
            cliente.Sexo = usuario.Sexo;
            cliente.Endereco = usuario.Endereco;
            cliente.Complemento = usuario.Complemento;
            cliente.Bairro = usuario.Bairro;
            cliente.CEP = usuario.CEP;
            cliente.PaisId = 1;
            cliente.CidadeId = usuario.CidadeId;
            cliente.EstadoId = usuario.EstadoId;
            cliente.Telefone = usuario.Telefone;
            cliente.Celular = usuario.Celular;
            cliente.WhatsApp = usuario.WhatsApp;

            ViewBag.Estado = _user.BuscarEstados().Select(x => new { x.EstadoId, x.Nome }).ToList();
            ViewBag.Cidade = _user.BuscarPorEstado(usuario.EstadoId).Select(x => new { x.CidadeId, x.Nome }).ToList();

            return View(cliente);
        }

        // POST: Admin/Úsuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioViewModel usuario)
        {
            if (SessionManager.IsAuthenticated == false) return RedirectToAction("Login", "Account");

            var cpf = usuario.CPF;
            if (Functions.ValidaCpf(cpf) == false)
                ModelState.AddModelError("CPF", "CPF Inválido...");

            if (ModelState.IsValid)
            {
                Usuario cliente = _user.RecuperarUsuarioPorEmail(usuario.Email);
                cliente.Id = usuario.UserId;
                cliente.PerfilUsuarioId = 2;
                cliente.Email = usuario.Email;
                cliente.Senha = cliente.Senha;
                cliente.UserName = usuario.Nome.ToUpper();
                cliente.Numero = usuario.Numero;
                cliente.DataNascimento = usuario.DataNascimento;
                cliente.CPF = usuario.CPF;
                cliente.Brasileiro = 0;
                cliente.Sexo = usuario.Sexo;
                cliente.Contato = usuario.Nome;
                cliente.FoneContato = usuario.Telefone;
                cliente.Endereco = usuario.Endereco;
                cliente.Complemento = usuario.Complemento;
                cliente.Bairro = usuario.Bairro;
                cliente.CEP = usuario.CEP;
                cliente.PaisId = 1;
                cliente.CidadeId = usuario.CidadeId;
                cliente.EstadoId = usuario.EstadoId;
                cliente.Telefone = usuario.Telefone;
                cliente.Celular = usuario.Celular;
                cliente.WhatsApp = usuario.WhatsApp;
                _user.CadastraUsuario(cliente);
                return RedirectToAction("Index", "Usuario");
            }

            ViewBag.Estado = _user.BuscarEstados().Select(x => new { x.EstadoId, x.Nome }).ToList();
            ViewBag.Cidade = _user.BuscarPorEstado(usuario.EstadoId).Select(x => new { x.CidadeId, x.Nome }).ToList();

            return View(usuario);
        }

        // POST: Admin/Categoria/Delete/5
        [HttpPost]
        public JsonResult DeleteUsuario(int id)
        {
            string mensagemErro = "Excluído com sucesso...";
            try
            {
                Usuario usuario = _user.GetById(id);
                _user.Remove(usuario);
            }
            catch (Exception ex)
            {
                mensagemErro = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
            }
            return Json(mensagemErro, JsonRequestBehavior.DenyGet);
        }
    }
}

EuCorro.MVC.Site/Controllers/CadastroController.cs
using Eucorro.Domain.Models;
using EuCorro.App.Interface;
using EuCorro.Service;
using EuCorro.MVC.Site.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace EuCorro.MVC.Site.Controllers
{
    public class CadastroController : Controller
    {
        private readonly IUsuarioApp _cadastro;

        public CadastroController(IUsuarioApp cadastro)
        {
            _cadastro = cadastro;
        }

        // GET: Cadastro
        public ActionResult Create()
        {
            ViewBag.Estado = _cadastro.BuscarEstados().Select(x => new { x.EstadoId, x.Nome }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ClienteId,PerfilUsuarioId,Login,Senha,Nome,DataNascimento,CPF,Email,Endereco,Numero,Complemento,Bairro,CEP,PaisId,CidadeId,EstadoId,Telefone,Operadora,WhatsApp,SKYPE,DataCadastro,Reentradas,Status,BancoId,Titular.TipoConta,Agencia,Conta,Operacao")] CadastroViewModel cadastroViewModel)
        public ActionResult Create(CadastroViewModel cadastroViewModel)
        {
            if (_cadastro.IsExistEmail(cadastroViewModel.Email))
                ModelState.AddModelError("Email", "E-mail cadastrado, tente outro...");

            var cpf = cadastroViewModel.CPF;
            if (Functions.ValidaCpf(cpf) == false)
                ModelState.AddModelError("CPF", "CPF Inválido...");

            var post = Request.Files[0];

            if (post == null)
            {
                ModelState.AddModelError("Foto", "Foto do Atleta inválida ou vazia, tente novamente !!!");
                return View();
            }

            if (post.FileName != "")
            {
                var arquivoDel = Path.Combine(Server.MapPath("~/Uploads/Atletas"), (string)Session["Arquivo"]);

                if (System.IO.File.Exists(@arquivoDel))
                {
                    try
                    {
                        System.IO.File.Delete(@arquivoDel);
                    }
                    catch (IOException e)
                    {
                        Console.WriteLine(e.Message);
                        return View();
                    }
                }
            }

            if (ModelState.IsValid)
            {
                var cliente = new Usuario();
                cliente.PerfilUsuarioId = 3;
                cliente.Email = cadastroViewModel.Email;
                cliente.Senha = cadastroViewModel.Senha;
                cliente.UserName = cadastroViewModel.Nome.ToUpper();
                cliente.Numero = cadastroViewModel.Numero;
                cliente.DataNascimento = cadastroViewModel.DataNascimento;
                cliente.Idade = DateTime.Now.Year - cadastroViewModel.DataNascimento.Year;
                cliente.CPF = cadastroViewModel.CPF;
                cliente.Camiseta = cadastroViewModel.Camiseta;
                cliente.Brasileiro = cadastroViewModel.Brasileiro;
                cliente.Sexo = cadastroViewModel.Sexo;
                cliente.Contato = cadastroViewModel.Contato;
                cliente.FoneContato = cadastroViewModel.FoneContato;
                cliente.Endereco = cadastroViewModel.Endereco;
                cliente.Complemento = cadastroViewModel.Complemento;
                cliente.Bairro = cadastroViewModel.Bairro;
                cliente.CEP = cadastroViewModel.CEP;
                cliente.PaisId = 1;
                cliente.CidadeId = cadastroViewModel.CidadeId;
                cliente.EstadoId = cadastroViewModel.EstadoId;
                cliente.Telefone = cadastroViewModel.Telefone;
                cliente.Celular = cadastroViewModel.Celular;
                cliente.WhatsApp = cadastroViewModel.WhatsApp;
                _cadastro.CadastraUsuario(cliente);
                return RedirectToAction("Index", "Home", new { Areas = "Clientes" });
            }
            return View(cadastroViewModel);
        }

        public JsonResult ValidarCPF(string cpf)
        {
            if (string.IsNullOrEmpty(cpf))
            {
                return Json("O campo CPF é obrigatório!", JsonRequestBehavior.AllowGet);
            }

            var retorno = _cadastro.BuscarCPF(cpf).CPF;
            if (!string.IsNullOrEmpty(retorno))
            {
                return Json("CPF já cadastrado!", JsonRequestBehavior.AllowGet);
            }

            if (Functions.ValidaCpf(cpf) == true)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("CPF inválido. Favor tente novamente!", JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ChecaEmail(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                return Json("O campo E-mail é obrigatório!", JsonRequestBehavior.AllowGet);
            }


            var encontrado = _cadastro.IsExistEmail(email);
            if (encontrado == false)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("CPF inválido. Favor tente novamente!", JsonRequestBehavior.AllowGet);
            }
        }

        private IEnumerable<Cidade> GetCidades(int estadoId)
        {
            return _cadastro.BuscarPorEstado(estadoId).ToList();
        }

        //[AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadCidadeId(string estadoId)
        {
            var cidadeList = GetCidades(Convert.ToInt32(estadoId));

            var cidadeData = cidadeList.Select(m => new SelectListItem
            {
                Text = m.Nome,
                Value = m.CidadeId.ToString(CultureInfo.InvariantCulture),
            });
            return Json(cidadeData, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Inscricao(int Evento)
        //{
        //    return View();
        //}
    }
}

EuCorro.MVC.Site/Areas/Admin/Views/Usuario/Create.cshtml
@model EuCorro.MVC.Site.ViewModels.UsuarioViewModel

@{
    ViewBag.Title = "Usuário";
    ViewBag.SubTitle = "Dados do Usuário";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

@section Menu {
    @Scripts.Render("~/Scripts/Cadastro/Usuario/menu")
}

<section class="body-content">
    @using (Html.BeginForm("Register", "Acfount", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewBag.SubTitle</h3>
            </div>
            <div class="box-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control textomaiusculo" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EnumDropDownListFor(model => model.Sexo, null, new { @class = "form-control no-block" })
                            @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control textomaiusculo" } })
                            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control textomaiusculo" } })
                            @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control textomaiusculo" } })
                            @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EstadoId, "Estado", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownListFor(model => model.EstadoId, new SelectList(ViewBag.Estado, "EstadoId", "Nome"), "Selecione o Estado...", new { @id = "ddlEstados", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CidadeId, "Cidade", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownListFor(model => model.CidadeId, Enumerable.Empty<SelectListItem>(), "Selecione a Cidade...", new { @id = "ddlCidades", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CidadeId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control Fone" } })
                            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control Fone" } })
                            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.WhatsApp, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.WhatsApp, new { htmlAttributes = new { @class = "form-control Fone" } })
                            @Html.ValidationMessageFor(model => model.WhatsApp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="box-footer">
                <div class="panel-footer form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-primary">Salvar Registros</button>
                        <a class="btn btn-danger" href="@Url.Action("Index")">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-validate/js")
    @Scripts.Render("~/AdminLTE/plugins/input-mask/js")
    @*@Scripts.Render("~/jqueryval/js")*@
    <script src="~/Scripts/CadastroAtleta/CadastroAtleta.js"></script>

    @*<script>

            $(document).ready(function () {

                var masks = ['(00) 00000-0000', '(00) 0000-00009'];

                //Código para contornar o conflito do jquery mask com o jquery validate
                $(function () {

                    //$('.Fone').mask("(99) 99990-9999");

                    $("#Telefone").mask(masks[1], {
                        onKeyPress: function (val, e, field, options) {
                            field.mask(val.length > 14 ? masks[0] : masks[1], options);
                        }
                    });
                    $("#FoneContato").mask(masks[1], {
                        onKeyPress: function (val, e, field, options) {
                            field.mask(val.length > 14 ? masks[0] : masks[1], options);
                        }
                    });
                    $("#Celular").mask(masks[1], {
                        onKeyPress: function (val, e, field, options) {
                            field.mask(val.length > 14 ? masks[0] : masks[1], options);
                        }
                    });
                    $("#WhatsApp").mask(masks[1], {
                        onKeyPress: function (val, e, field, options) {
                            field.mask(val.length > 14 ? masks[0] : masks[1], options);
                        }
                    });

                    $("#CPF").mask("999.999.999-99");
                    $("#CEP").mask("99.999-999");
                    $("#DataNascimento").mask("99/99/9999");

                    $("#ddlEstados").on("change", function () {
                        var estadoId = $(this).val();
                        //var url = '@Url.Action("LoadCidadeId", "Cadastro")';
                        var url = '/Cadastro/LoadCidadeId/';
                        $.getJSON(url, { estadoId: estadoId },
                            function (estadosData) {
                                $("#ddlCidades :gt(0)").remove();
                                var select = $("#ddlCidades");
                                select.attr('disabled', false);
                                select.empty();
                                select.append($('<option/>', {
                                    value: 0,
                                    text: "Selecione a Cidade... "
                                }));
                                $.each(estadosData, function (index, itemData) {
                                    //alert(estadosData);
                                    //alert(itemData);
                                    select.append($('<option/>', {
                                        value: itemData.Value,
                                        text: itemData.Text
                                    }));
                                });
                            });
                    });

                });

            });

        </script>*@
}